export const cityUrlEndpoint = "https://core.shoplover.com/sll/v1/states";
export const categoryUrlEndpoint = "https://ims.shoplover.com/sll/v1/categories";
export const subcategoryUrlEndpoint = "https://ims.shoplover.com/sll/v1/sub_categories";
export const locationUrlEndpoint = "https://ims.shoplover.com/sll/v1/all_location";
export const brandUrlEndpoint = "https://ims.shoplover.com/sll/v1/brands";
export const orderedProductEndpoint = "https://core.shoplover.com/sll/v1/report/customer-order-product-category-sales-total-report";
export const publishedProductEndpoint = "https://core.shoplover.com/sll/v1/report/sellers-published-admin-total-product-report";
export const pendingProductEndpoint = "https://core.shoplover.com/sll/v1/report/pending-approved-total-sellers-report";
export const dailyMonthlyNewCustomers = "https://core.shoplover.com/sll/v1/report/customer/daily-monthly-new-customer-total-report";
export const monthlyOrders = "https://core.shoplover.com/sll/v1/report/customer/monthly-order-total-report";
export const orderChannel = "https://core.shoplover.com/sll/v1/report/customer/order-channel";
export const topCategories = "https://core.shoplover.com/sll/v1/top-categories";
export const inventoryEndpoint = "https://ims.shoplover.com/sll/v1/report/"
export const paymentChannelEndpoint = "https://oms.shoplover.com/sll/crp/payment-channel-sales"
export const categoryWiseSalesReport = "https://core.shoplover.com/sll/v1/report/customers/category-wise-sales-report"
export const sellerWiseSalesReport = "https://core.shoplover.com/sll/v1/report/customers/seller-wise-sales-report"
export const topTenDistrictsEndPoint = "https://oms.shoplover.com/sll/crp/district-wise-sales"
export const topTenItemsEndPoint = "https://core.shoplover.com/sll/v1/report/items/top-ten-items"
export const crpOrderStatusReport = "https://dms.shoplover.com/api/crp-status-summary-v2"
export const lastHourVisitor = " https://trackapi.shoplover.com/api/crp/active_visitor_comparison"
export const sessionTimeComparison = " https://trackapi.shoplover.com/api/crp/session_time_comparison"
export const pageViewsEndPoint = " https://trackapi.shoplover.com/api/crp/page_view_comparison"
export const goalsActiveUserComparison = " https://trackapi.shoplover.com/api/crp/goals_active_user_comparison"
export const sourceAnalyticComparison = " https://trackapi.shoplover.com/api/crp/sources_analytics_comparison"
export const insideOutsideDhakaEndpoint = "https://dms.shoplover.com/api/"
export const monthlyAnalyticsEndPoint = " https://trackapi.shoplover.com/api/crp/monthly_active_users_analytics"
export const logisticApiKey = "SLPSxORF2HppFbSicmxRWIwPsK990gtXGAgmth3YD"
export const paymentChannelApiKey = "ZOHYSUHIRZS_LBM!@050PA5-POMU0ZBX-@WY)=5XP&)B#05*G"